from setuptools import setup, find_packages

setup(
    name='qmpy',
    version='1.2.0',
    author='S. Kirklin',
    author_email='scott.kirklin@gmail.com',
    license='LICENSE.txt',
    classifiers=["Programming Language :: Python :: 2.7"],
    packages=find_packages(),
    scripts=['bin/oqmd', 'bin/qmpy'],
    url='http://pypi.python.org/pypi/qmpy',
    description='Suite of computational materials science tools',
    include_package_data=True,
    long_description=open('README.md').read(),
    install_requires=[
        "Django == 1.8.18",
        "PuLP",
        "numpy",
        "scipy",
        "MySQL-python",
        "matplotlib",
        "networkx",
        "pytest",
        "python-memcached",
        "ase",
        "django-extensions",
        "lxml",
        "spglib",
        "PyCifRW",
        "pexpect",
        "pyparsing",
        "PyYAML",
        "scikit-learn",
        "bokeh",
        "djangorestframework == 3.6.4",
        "djangorestframework-xml",
        "djangorestframework-yaml",
        "djangorestframework-queryfields == 1.0.0",
        "djangorestframework-filters == 0.11.1",
        "django-crispy-forms",
        "lark-parser",
        "requests"
    ],
)
